[[redirects]]
  from = "/api/*"
  to = "http://13.60.250.160:8000/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_GA_TRACKING_ID = "G-CVRLXZ6V3C"
  VITE_DISABLE_GA = "false"
